name: repetition_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  
  sqflite: ^2.3.0
  path: ^1.8.3
  file_picker: ^10.3.1  # PACKAGE POUR LA SELECTION DES FICHIER 
  flutter_datetime_picker: ^1.5.1
  fl_chart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
